name: Test HI 2011 workflow on plain docker
on:
  pull_request:
    branches:
    - 2011
jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: HiForest test - plain docker
    steps:
      # chmod of the script before getting to the container
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          mkdir outputs
          pwd
          ls -l
          chmod +x commands.sh
      # run the container with the script in the repository
      - name: Producer
        id: container
        run: | 
          docker run -v $(pwd):/mnt/vol -w /home/cmsusr gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cmssw_4_4_7-slc5_amd64_gcc434:2020-11-19-89e805d7 /bin/bash /mnt/vol/commands.sh 10000
          echo ls -l  `ls -l `
          cp *.root outputs
          cp *.png outputs
      # upload output file
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: outputs/
